name: Xanalia-minting-single/launchpad.xana.net Subdomain
on:
  push:
    branches:
      - production
  
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
#         here will will set node version 14
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14
        
      - name: Install dependencies
        run: npm install

      - name: Build
        run: CI=false npm run build
        
      - uses: jakejarvis/s3-sync-action@master
        name: Upload App to S3 Bucket
#         Here we have to upload code with publicly access
        with:
          args: --acl public-read
        env:
          AWS_S3_BUCKET: launchpad-land-xana
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          SOURCE_DIR: 'build'
          
      - name: Create CloudFront Cache Invalidation
        uses: chetan/invalidate-cloudfront-action@master
        env:
#         Note: we have to mention region of aws here like this not in as veriable
          AWS_REGION: ap-southeast-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DISTRIBUTION: E162YB2HCY59W8
          PATHS: '/*'
          
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow # selectable (default: repo,message)
        env:
          SLACK_CHANNEL: '#github-action'
          SLACK_COLOR: ${{ job.status }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }} # required
        if: always() # Pick up events even if the job fails or is canceled.
